include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_specify_types: true
    avoid_print: true
    prefer_const_constructors: true
    prefer_final_fields: true
    use_key_in_widget_constructors: true

analyzer:
  exclude:
    - "**/*.g.dart"
