name: dev_connect

description: "Uma plataforma de conexão para desenvolvedores."

publish_to: 'none' 

version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^15.1.2
  mobx: ^2.3.0
  flutter_mobx: ^2.2.0
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  validatorless: ^1.2.5
  google_fonts: ^5.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.0
  get_it: ^8.2.0
  json_annotation: ^4.8.0
  flutter_dotenv: ^5.0.2
  loading_animation_widget: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  json_serializable: ^6.6.1
  mobx_codegen: ^2.7.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/logo.png"
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash.png
  android: true
  ios: false

flutter:
  uses-material-design: true
  assets:
    - .env
