name: dev_connect

description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
 # Gerenciamento de rotas
  go_router: ^15.1.2

  # Gerenciamento de estado
  mobx: ^2.3.0
  flutter_mobx: ^2.2.0
  # Requisições HTTP
  dio: ^5.4.0
  # Armazenamento local
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/logo.png"
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash.png
  android: true
  ios: false

flutter:
  uses-material-design: true
